### ISSUE TITLE
Running Shape Analysis with default options results in slicer.util.MRMLNodeNotFoundException

### ISSUE THREAD

**Issue by lassoan** [Kitware/SlicerSALT#122]
SlicerSALT 1.0 on Windows

The problem is most likely due to that `slicer.util.getNode()` throws an exception (API changed several months ago). This method should not be used in production code but only for interactive use/testing. Instead `slicer.mrmlScene.GetFirstNodeByName()` method may be used. Both should be avoided because several nodes may have the same name in a scene, so node name is not suitable for identifying a node.

Error message:
```
Loading Slicer RC file [C:/Users/andra/.slicerrc.py]
Widget: Running ShapeAnalysisModule
-- Scheduled : ShapeAnalysisModule
3 case(s) found
-- Running : ShapeAnalysisModule
Traceback (most recent call last):
  File "C:/Program Files/SlicerSALT 1.0.0/bin/../lib/SlicerSALT-4.9/qt-scripted-modules/ShapeAnalysisModule.py", line 626, in onApplyButton
    self.Logic.ShapeAnalysisCases()
  File "C:/Program Files/SlicerSALT 1.0.0/bin/../lib/SlicerSALT-4.9/qt-scripted-modules/ShapeAnalysisModule.py", line 1194, in ShapeAnalysisCases
    self.startPipeline(0)
  File "C:\Program Files\SlicerSALT 1.0.0\lib\SlicerSALT-4.9\qt-scripted-modules\CommonUtilities\LogicMixin.py", line 31, in startPipeline
    self.pipeline[id].setup()
  File "C:/Program Files/SlicerSALT 1.0.0/bin/../lib/SlicerSALT-4.9/qt-scripted-modules/ShapeAnalysisModule.py", line 1423, in setup
    pp_output_node = MRMLUtility.loadMRMLNode(PostProcessOutputRootname, PostProcessOutputDirectory, PostProcessOutputFilename, 'LabelMap')
  File "C:\Program Files\SlicerSALT 1.0.0\lib\SlicerSALT-4.9\qt-scripted-modules\CommonUtilities\utility.py", line 16, in loadMRMLNode
    node = slicer.util.getNode(node_name)
  File "C:\Program Files\SlicerSALT 1.0.0\bin\Python\slicer\util.py", line 670, in getNode
    raise MRMLNodeNotFoundException("could not find nodes in the scene by name or id '%s'" % (pattern if (type(pattern) == str) else ""))
slicer.util.MRMLNodeNotFoundException: could not find nodes in the scene by name or id 'OutputImage_pp'
```

**Comment by lassoan** [comment]
Pull request submitted with a proposed fix: https://github.com/NIRALUser/SPHARM-PDM/pull/39

**Comment by bpaniagua** [comment]
Thank you so much @lassoan !!

**Comment by lassoan** [comment]
Thanks for merging. Let us know when you have a SlicerSALT or SPHARM-PDM release that is ready to use. 

We set Slicer ExtensionIndex for all of our extensions so that Slicer nightly builds always uses master branch of our extensions. This way whenever there are any fixes or improvements in the master branch they become available to all users automatically the next day. I would recommend to do the same for SPHARM-PDM extension.

**Comment by mattjolley** [comment]
@lassoan 

Great work!  The Ferrari strikes again.

**Comment by jcfr** [comment]
> always uses master branch

We will switch to this approach too
