### ISSUE TITLE
SampleData for DataImporter is not loading the whole dataset

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#210]

**Comment by bpaniagua** [comment]
loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.
loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.
loadNodeFromFile `returnNode` argument is deprecated. Loaded node is now returned directly if `returnNode` is not specified.
Traceback (most recent call last):
  File "/work/Projects/SlicerSALT/development/SlicerSALT-build/Slicer-build/lib/SlicerSALT-4.11/qt-scripted-modules/DataImporter.py", line 1705, in onClickImportButton
    self.importFiles(self.filteredFilePathsList)
  File "/work/Projects/SlicerSALT/development/SlicerSALT-build/Slicer-build/lib/SlicerSALT-4.11/qt-scripted-modules/DataImporter.py", line 1303, in importFiles
    self.logic.populateTopologyDictionary()
  File "/work/Projects/SlicerSALT/development/SlicerSALT-build/Slicer-build/lib/SlicerSALT-4.11/qt-scripted-modules/DataImporter.py", line 504, in populateTopologyDictionary
    polydata = segmentationNode.GetClosedSurfaceRepresentation(segmentId)
TypeError: GetClosedSurfaceRepresentation() takes exactly 2 arguments (1 given)
