### ISSUE TITLE
BUG: Python errors on start

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#72]
```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/Slicer-build/lib/SlicerSALT-4.9/qt-scripted-modules/DICOM.py", line 11, in <module>
    import DICOMLib
  File "/work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/Slicer-build/lib/SlicerSALT-4.9/qt-scripted-modules/DICOMLib/__init__.py", line 4, in <module>
    from DICOMWidgets import *
  File "/work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/Slicer-build/lib/SlicerSALT-4.9/qt-scripted-modules/DICOMLib/DICOMWidgets.py", line 6, in <module>
    from packaging import version
ImportError: No module named packaging
loadSourceAsModule - Failed to load file "/work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/Slicer-build/lib/SlicerSALT-4.9/qt-scripted-modules/DICOM.py"  as module "DICOM" ! 
Fail to instantiate module  "DICOM" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/Slicer-build/lib/SlicerSALT-4.9/qt-scripted-modules/DICOMScalarVolumePlugin.py", line 4, in <module>
    from DICOMLib import DICOMPlugin
  File "/work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/Slicer-build/lib/SlicerSALT-4.9/qt-scripted-modules/DICOMLib/__init__.py", line 4, in <module>
    from DICOMWidgets import *
  File "/work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/Slicer-build/lib/SlicerSALT-4.9/qt-scripted-modules/DICOMLib/DICOMWidgets.py", line 6, in <module>
    from packaging import version
ImportError: No module named packaging
loadSourceAsModule - Failed to load file "/work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/Slicer-build/lib/SlicerSALT-4.9/qt-scripted-modules/DICOMScalarVolumePlugin.py"  as module "DICOMScalarVolumePlugin" ! 
Fail to instantiate module  "DICOMScalarVolumePlugin" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/Slicer-build/lib/SlicerSALT-4.9/qt-scripted-modules/DICOMSlicerDataBundlePlugin.py", line 3, in <module>
    from DICOMLib import DICOMPlugin
  File "/work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/Slicer-build/lib/SlicerSALT-4.9/qt-scripted-modules/DICOMLib/__init__.py", line 4, in <module>
    from DICOMWidgets import *
  File "/work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/Slicer-build/lib/SlicerSALT-4.9/qt-scripted-modules/DICOMLib/DICOMWidgets.py", line 6, in <module>
    from packaging import version
ImportError: No module named packaging
loadSourceAsModule - Failed to load file "/work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/Slicer-build/lib/SlicerSALT-4.9/qt-scripted-modules/DICOMSlicerDataBundlePlugin.py"  as module "DICOMSlicerDataBundlePlugin" ! 
Fail to instantiate module  "DICOMSlicerDataBundlePlugin" 
  Error(s):
    Failed to find python interpreter for CLI: /work/Projects/slicerSALT/slicerSALT-Dashboards/Nightly/SlicerSALT-0-build/Slicer-build/lib/SlicerSALT-4.9/cli-modules/PyCLIModule4Test.py
Fail to instantiate module  "PyCLI4Test" 
When loading module  "DICOMPatcher" , the dependency "DICOM" failed to be loaded. 
Object::connect: No such signal qSlicerGPUMemoryComboBox::currentTextChanged(QString)
Object::connect:  (sender name:   'GPUMemoryComboBox')
Object::connect:  (receiver name: 'qSlicerVolumeRenderingSettingsPanel')
Switch to module:  "Home" 
```

**Comment by jcfr** [comment]
> from packaging import version
> ImportError: No module named packaging

This was fixed in the latest version of SlicerSALT using a newer Slicer.

**Comment by jcfr** [comment]
Please, re-open if still an issue
